//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WACamping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class location
    {
        public int quantite { get; set; }
        public string duree_loc { get; set; }
        public int Id_sejour { get; set; }
        public int Id_option { get; set; }
    
        public virtual option option { get; set; }
        public virtual sejour sejour { get; set; }
    }
}
